### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by ShavidzeT** [thecotne/devtime-ge#14]
ტრევისის ჩამატებაზე ვფიქრობდი.

დოკებში გიწერია ახსნა, თუ "როგორ ჩავრთოთ ლოკალური ვერსია" და ბოლოს როგორც მახსოვს რაღაც პრობლემები შეიქმნა ჯეკილის ლოკალურ კომპზე ასაწევად.

ხოდა ტრევისზე ხო არ გავიტანოთ ამის ტესტები, მაგალითად თუ ისერვება პროექტი ლოკალურად და რაღაც რუღაცეები...

**Comment by thecotne** [comment]
არა
